### PR TITLE
Add badges to readme

### PR DESCRIPTION
**Pull request by soda480**
Add relevant badges to readme

Signed-off-by: Emilio Reyes <emilio.reyes@intel.com>

### CODE REVIEW

**Review by bnevis-i — COMMENTED** [review]
Committers link, https://github.com/orgs/edgexfoundry/teams/security-pipeline-policies-committers/members, is broken.

**Comment by soda480** [comment]
> Committers link, https://github.com/orgs/edgexfoundry/teams/security-pipeline-policies-committers/members, is broken.

Yeah, there is something odd about this repo; there is no team in `edgexfoundry` setup for this repo - which is inconsistent with how all the other repos have been setup.  Maybe this is by design, I'm not sure. For now I will remove the committers badge from the README.

**Comment by ernestojeda** [comment]
Badges seem irrelevant here. I will close this PR

**Comment by soda480** [comment]
closing PR - irrelevant

**Pull request closed without merging**
